export const vendorProfile = {
  companyName: 'טכנולוגיות אורן בע"מ',
  companySize: 'עסק קטן-בינוני (18 עובדים)',
  techStack: ['React', 'Node.js', '.NET', 'PostgreSQL', 'Azure'],
  specialties: ['פיתוח מערכות ווב', 'אינטגרציות API', 'ניהול פרויקטים ממשלתיים'],
  yearsOfExperience: 7,
  hasMobileExperience: false,
  averageTechnicalScore: 78,
}

// Used internally by the analysis engine — not displayed directly in the UI.
export const tenderHistory = [
  {
    tenderName: 'מכרז דיגיטציה - משרד התחבורה',
    outcome: 'Lost',
    committeeFeedback: 'ההצעה הכספית הייתה גבוהה ב-14% מההצעה הזוכה, למרות ניקוד טכני תקין.',
    priceGapPercent: 14,
    technicalScore: 82,
    wasDisqualified: false,
    requiredCapabilities: ['React', 'Node.js', 'PostgreSQL'],
  },
  {
    tenderName: 'מכרז פורטל שירות - עיריית השרון',
    outcome: 'Lost',
    committeeFeedback: 'נפסלת עקב חוסר בניסיון מוכח בפיתוח אפליקציות מובייל, שהיה דרישת סף.',
    priceGapPercent: null,
    technicalScore: 65,
    wasDisqualified: true,
    requiredCapabilities: ['React', 'Mobile', '.NET'],
  },
  {
    tenderName: 'מכרז מערכת CRM - משרד הכלכלה',
    outcome: 'Won',
    committeeFeedback: 'הצעה מאוזנת עם ניקוד טכני גבוה והתאמה מלאה לדרישות.',
    priceGapPercent: 2,
    technicalScore: 88,
    wasDisqualified: false,
    requiredCapabilities: ['React', 'Node.js', '.NET'],
  },
  {
    tenderName: 'מכרז תשתיות ענן - רשות המסים',
    outcome: 'Lost',
    committeeFeedback: 'ההצעה הכספית הייתה גבוהה ב-11% מהזוכה, על אף עמידה בכל דרישות הסף הטכניות.',
    priceGapPercent: 11,
    technicalScore: 75,
    wasDisqualified: false,
    requiredCapabilities: ['Azure', '.NET', 'PostgreSQL'],
  },
]

export const tenders = [
  {
    id: 1,
    tenderName: 'פיתוח פורטל אזרח דיגיטלי',
    publishingBody: 'משרד הפנים',
    category: 'פורטלים ממשלתיים',
    tenderType: 'מכרז',
    referenceNumber: '1000822801',
    publishedDate: '2025-01-13',
    description: 'פיתוח והטמעה של פורטל שירות דיגיטלי לאזרח, כולל אפליקציית מובייל נלווית, בטכנולוגיית React ו-.NET.',
    minimumThresholdScore: 70,
    requiredCapabilities: ['React', '.NET', 'Mobile', 'PostgreSQL'],
    requiresMobileExperience: true,
    estimatedBudget: 1200000,
    submissionDeadline: '2026-08-15',
  },
  {
    id: 2,
    tenderName: 'מערכת ניהול תורים דיגיטלית',
    publishingBody: 'משרד הבריאות',
    category: 'מערכות בריאות',
    tenderType: 'מכרז',
    referenceNumber: '1000822802',
    publishedDate: '2025-01-27',
    description: 'הקמת מערכת ניהול תורים ארצית למרפאות ממשלתיות, כולל ממשק ניהול וממשק אזרח.',
    minimumThresholdScore: 65,
    requiredCapabilities: ['React', 'Node.js', 'MongoDB'],
    requiresMobileExperience: false,
    estimatedBudget: 450000,
    submissionDeadline: '2026-07-30',
  },
  {
    id: 3,
    tenderName: 'אפליקציית שירותי רווחה לאזרח',
    publishingBody: 'משרד הרווחה',
    category: 'אפליקציות מובייל',
    tenderType: 'מכרז דינמי',
    referenceNumber: '1000822803',
    publishedDate: '2025-02-10',
    description: 'פיתוח אפליקציה ניידת למיצוי זכויות ושירותי רווחה, כולל התממשקות למאגרי מידע ממשלתיים.',
    minimumThresholdScore: 75,
    requiredCapabilities: ['React Native', 'Node.js', 'Mobile'],
    requiresMobileExperience: true,
    estimatedBudget: 680000,
    submissionDeadline: '2026-09-01',
  },
  {
    id: 4,
    tenderName: 'מערכת CRM ארצית לגביית מס',
    publishingBody: 'רשות המסים',
    category: 'מערכות ליבה',
    tenderType: 'מכרז',
    referenceNumber: '1000822804',
    publishedDate: '2025-02-24',
    description: 'פיתוח מערכת CRM מקיפה לניהול פניות נישומים, כולל אינטגרציה עם מערכות גבייה קיימות.',
    minimumThresholdScore: 80,
    requiredCapabilities: ['.NET', 'PostgreSQL', 'Azure'],
    requiresMobileExperience: false,
    estimatedBudget: 2300000,
    submissionDeadline: '2026-08-20',
  },
  {
    id: 5,
    tenderName: 'פלטפורמת דוחות וניתוח נתונים',
    publishingBody: 'משרד האוצר',
    category: 'BI ואנליטיקה',
    tenderType: 'מכרז',
    referenceNumber: '1000822805',
    publishedDate: '2025-03-10',
    description: 'הקמת פלטפורמת BI לניתוח תקציבי משרדי ממשלה, כולל דשבורדים אינטראקטיביים.',
    minimumThresholdScore: 72,
    requiredCapabilities: ['Power BI', 'SQL Server', '.NET'],
    requiresMobileExperience: false,
    estimatedBudget: 900000,
    submissionDeadline: '2026-07-25',
  },
  {
    id: 6,
    tenderName: 'מערכת ניהול מלגות סטודנטים',
    publishingBody: 'משרד החינוך',
    category: 'מערכות ליבה',
    tenderType: 'מכרז דינמי',
    referenceNumber: '1000822806',
    publishedDate: '2025-03-24',
    description: 'פיתוח מערכת דיגיטלית לניהול בקשות ואישורי מלגות עבור סטודנטים ברחבי הארץ.',
    minimumThresholdScore: 60,
    requiredCapabilities: ['React', 'Node.js', 'PostgreSQL'],
    requiresMobileExperience: false,
    estimatedBudget: 350000,
    submissionDeadline: '2026-07-10',
  },
  {
    id: 7,
    tenderName: 'אתר ומערכת הזמנות מקוונת',
    publishingBody: 'רשות הטבע והגנים',
    category: 'אתרים ומסחר',
    tenderType: 'מכרז',
    referenceNumber: '1000822807',
    publishedDate: '2025-04-07',
    description: 'הקמת אתר תדמיתי ומערכת הזמנת כרטיסים מקוונת לשמורות טבע ואתרי לאום.',
    minimumThresholdScore: 55,
    requiredCapabilities: ['React', 'Node.js', 'MongoDB'],
    requiresMobileExperience: false,
    estimatedBudget: 280000,
    submissionDeadline: '2026-08-05',
  },
  {
    id: 8,
    tenderName: 'פורטל ספקים ומכרזים מאובטח',
    publishingBody: 'משרד הביטחון',
    category: 'פורטלים ממשלתיים',
    tenderType: 'מכרז',
    referenceNumber: '1000822808',
    publishedDate: '2025-04-21',
    description: 'פיתוח פורטל מאובטח לניהול מכרזים וספקים ברמת סיווג גבוהה, כולל בקרות אבטחת מידע מחמירות.',
    minimumThresholdScore: 85,
    requiredCapabilities: ['.NET', 'Azure', 'PostgreSQL', 'Cybersecurity'],
    requiresMobileExperience: false,
    estimatedBudget: 3000000,
    submissionDeadline: '2026-09-10',
  },
  {
    id: 9,
    tenderName: 'אפליקציית ניוד עירוני חכם',
    publishingBody: 'עיריית תל אביב-יפו',
    category: 'אפליקציות מובייל',
    tenderType: 'מכרז דינמי',
    referenceNumber: '1000822809',
    publishedDate: '2025-05-05',
    description: 'פיתוח אפליקציה לניהול תחבורה עירונית משותפת, כולל מעקב GPS בזמן אמת.',
    minimumThresholdScore: 70,
    requiredCapabilities: ['React Native', 'Node.js', 'Mobile'],
    requiresMobileExperience: true,
    estimatedBudget: 1500000,
    submissionDeadline: '2026-08-28',
  },
  {
    id: 10,
    tenderName: 'מערכת ניהול אירועים ורישוי',
    publishingBody: 'עיריית ירושלים',
    category: 'מערכות ליבה',
    tenderType: 'מכרז',
    referenceNumber: '1000822810',
    publishedDate: '2025-05-19',
    description: 'פיתוח מערכת דיגיטלית לניהול בקשות רישוי אירועים עירוניים ומעקב אחר סטטוס טיפול.',
    minimumThresholdScore: 65,
    requiredCapabilities: ['React', '.NET'],
    requiresMobileExperience: false,
    estimatedBudget: 620000,
    submissionDeadline: '2026-07-18',
  },
  {
    id: 11,
    tenderName: 'מערכת בקרת תשתיות IoT',
    publishingBody: 'חברת החשמל',
    category: 'תשתיות וענן',
    tenderType: 'מכרז',
    referenceNumber: '1000822811',
    publishedDate: '2025-06-02',
    description: 'הקמת מערכת ניטור ובקרה בזמן אמת לתחנות חשמל מבוססת חיישני IoT ועיבוד נתונים בענן.',
    minimumThresholdScore: 78,
    requiredCapabilities: ['Python', 'AWS', 'Docker', 'IoT'],
    requiresMobileExperience: false,
    estimatedBudget: 4200000,
    submissionDeadline: '2026-09-20',
  },
  {
    id: 12,
    tenderName: 'פורטל שירות דיגיטלי לציבור',
    publishingBody: 'המוסד לביטוח לאומי',
    category: 'פורטלים ממשלתיים',
    tenderType: 'מכרז דינמי',
    referenceNumber: '1000822812',
    publishedDate: '2025-06-16',
    description: 'שדרוג פורטל השירות הדיגיטלי לאזרח, כולל אפליקציית מובייל מלווה ותהליכי הזדהות מאובטחים.',
    minimumThresholdScore: 82,
    requiredCapabilities: ['React', 'Node.js', 'PostgreSQL', 'Mobile'],
    requiresMobileExperience: true,
    estimatedBudget: 2800000,
    submissionDeadline: '2026-08-12',
  },
  {
    id: 13,
    tenderName: 'מערכת CRM ללקוחות עסקיים',
    publishingBody: 'בנק ישראל',
    category: 'מערכות ליבה',
    tenderType: 'מכרז',
    referenceNumber: '1000822813',
    publishedDate: '2025-06-30',
    description: 'פיתוח מערכת CRM מאובטחת לניהול קשרי גורמים מפוקחים, ברמת אבטחת מידע גבוהה במיוחד.',
    minimumThresholdScore: 88,
    requiredCapabilities: ['.NET', 'Azure', 'SQL Server'],
    requiresMobileExperience: false,
    estimatedBudget: 3600000,
    submissionDeadline: '2026-09-25',
  },
  {
    id: 14,
    tenderName: 'אפליקציית התנדבות קהילתית',
    publishingBody: 'עמותת "יד ביד"',
    category: 'אפליקציות מובייל',
    tenderType: 'מכרז',
    referenceNumber: '1000822814',
    publishedDate: '2025-07-14',
    description: 'פיתוח אפליקציה לחיבור בין מתנדבים לנזקקים באזור המגורים, כולל התראות בזמן אמת.',
    minimumThresholdScore: 50,
    requiredCapabilities: ['React Native', 'Firebase', 'Mobile'],
    requiresMobileExperience: true,
    estimatedBudget: 180000,
    submissionDeadline: '2026-07-08',
  },
  {
    id: 15,
    tenderName: 'מערכת ניהול מלאי חקלאי',
    publishingBody: 'משרד החקלאות',
    category: 'מערכות ליבה',
    tenderType: 'מכרז דינמי',
    referenceNumber: '1000822815',
    publishedDate: '2025-07-28',
    description: 'פיתוח מערכת דיגיטלית למעקב אחר מלאי תוצרת חקלאית ותכנון הפצה ארצית.',
    minimumThresholdScore: 58,
    requiredCapabilities: ['Node.js', 'MongoDB'],
    requiresMobileExperience: false,
    estimatedBudget: 320000,
    submissionDeadline: '2026-07-22',
  },
  {
    id: 16,
    tenderName: 'פלטפורמת אבחון מקוון',
    publishingBody: 'משרד הבריאות',
    category: 'בינה מלאכותית',
    tenderType: 'מכרז',
    referenceNumber: '1000822816',
    publishedDate: '2025-08-11',
    description: 'הקמת פלטפורמה מבוססת בינה מלאכותית לאבחון מקדים מרחוק בליווי צוות רפואי.',
    minimumThresholdScore: 76,
    requiredCapabilities: ['React', 'Python', 'AI/ML'],
    requiresMobileExperience: false,
    estimatedBudget: 1100000,
    submissionDeadline: '2026-08-30',
  },
  {
    id: 17,
    tenderName: 'מערכת ניהול פרויקטים ממשלתית',
    publishingBody: 'משרד הבינוי והשיכון',
    category: 'מערכות ליבה',
    tenderType: 'מכרז',
    referenceNumber: '1000822817',
    publishedDate: '2025-08-25',
    description: 'פיתוח מערכת מרכזית למעקב אחר פרויקטי בנייה ותשתית ברמה הארצית.',
    minimumThresholdScore: 74,
    requiredCapabilities: ['.NET', 'PostgreSQL', 'Azure'],
    requiresMobileExperience: false,
    estimatedBudget: 1750000,
    submissionDeadline: '2026-08-18',
  },
  {
    id: 18,
    tenderName: 'אפליקציית דיווח תקלות עירוני',
    publishingBody: 'עיריית חיפה',
    category: 'אפליקציות מובייל',
    tenderType: 'מכרז דינמי',
    referenceNumber: '1000822818',
    publishedDate: '2025-09-08',
    description: 'פיתוח אפליקציה לדיווח אזרחי על תקלות תשתית ומעקב אחר הטיפול בזמן אמת.',
    minimumThresholdScore: 68,
    requiredCapabilities: ['React Native', 'Node.js', 'Mobile'],
    requiresMobileExperience: true,
    estimatedBudget: 540000,
    submissionDeadline: '2026-07-28',
  },
  {
    id: 19,
    tenderName: 'מערכת סייבר והגנת מידע',
    publishingBody: 'הרשות הלאומית להגנת הסייבר',
    category: 'סייבר ואבטחת מידע',
    tenderType: 'מכרז',
    referenceNumber: '1000822819',
    publishedDate: '2025-09-22',
    description: 'הקמת מערכת ניטור ותגובה לאירועי סייבר עבור גופי ממשלה קריטיים.',
    minimumThresholdScore: 90,
    requiredCapabilities: ['Python', 'Cybersecurity', 'Docker'],
    requiresMobileExperience: false,
    estimatedBudget: 5000000,
    submissionDeadline: '2026-10-01',
  },
  {
    id: 20,
    tenderName: 'פורטל מידע תיירותי ארצי',
    publishingBody: 'משרד התיירות',
    category: 'אתרים ומסחר',
    tenderType: 'מכרז',
    referenceNumber: '1000822820',
    publishedDate: '2025-10-06',
    description: 'פיתוח פורטל מידע תיירותי רב-לשוני עם מנוע חיפוש אטרקציות ואירועים.',
    minimumThresholdScore: 55,
    requiredCapabilities: ['React', 'Node.js', 'MongoDB'],
    requiresMobileExperience: false,
    estimatedBudget: 400000,
    submissionDeadline: '2026-07-14',
  },
  {
    id: 21,
    tenderName: 'מערכת ניהול צי רכב ממשלתי',
    publishingBody: 'משרד התחבורה',
    category: 'תשתיות וענן',
    tenderType: 'מכרז דינמי',
    referenceNumber: '1000822821',
    publishedDate: '2025-10-20',
    description: 'פיתוח מערכת מעקב ותחזוקה לצי הרכב הממשלתי, כולל חיישני IoT לרכבים.',
    minimumThresholdScore: 71,
    requiredCapabilities: ['.NET', 'PostgreSQL', 'IoT'],
    requiresMobileExperience: false,
    estimatedBudget: 980000,
    submissionDeadline: '2026-08-22',
  },
  {
    id: 22,
    tenderName: 'אפליקציית בריאות דיגיטלית לקשיש',
    publishingBody: 'קופת חולים כללית',
    category: 'אפליקציות מובייל',
    tenderType: 'מכרז',
    referenceNumber: '1000822822',
    publishedDate: '2025-11-03',
    description: 'פיתוח אפליקציה ידידותית לקשיש למעקב תרופות ותורים רפואיים, כולל התראות בני משפחה.',
    minimumThresholdScore: 79,
    requiredCapabilities: ['React Native', 'Mobile', 'Node.js'],
    requiresMobileExperience: true,
    estimatedBudget: 1650000,
    submissionDeadline: '2026-09-05',
  },
]
